// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPq9YQsvf9nTExf7VpOWQ7H0NNwd9g2aw',
    appId: '1:859418712794:web:6048124a115a3aa91ea3e3',
    messagingSenderId: '859418712794',
    projectId: 'delivery-service-database',
    authDomain: 'delivery-service-database.firebaseapp.com',
    storageBucket: 'delivery-service-database.appspot.com',
    measurementId: 'G-WZZ09D2N1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7HRfyA9XiNsS2c2A9C_QdqRnh4_EpDQ',
    appId: '1:859418712794:android:b5f0c1c1d6fe488d1ea3e3',
    messagingSenderId: '859418712794',
    projectId: 'delivery-service-database',
    storageBucket: 'delivery-service-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9OvOPXDvox_v7aS5DCNG08wPKoMbA5F4',
    appId: '1:859418712794:ios:485af993ce4a49c81ea3e3',
    messagingSenderId: '859418712794',
    projectId: 'delivery-service-database',
    storageBucket: 'delivery-service-database.appspot.com',
    iosBundleId: 'com.example.deliveryServiceUser',
  );
}
